_wandb:
    value:
        cli_version: 0.28.1
        e:
            n6ip4c2o9ll2jnl1k3yecbslm4eq9yge:
                codePath: src_python\tune.py
                codePathLocal: src_python\tune.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "487890874368"
                        used: "217142566912"
                email: devamucaj@gmail.com
                executable: C:\Users\devam\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: 39a345ff033e4d70734083ae4a72d23ea7566523
                    remote: https://github.com/devs-glitch/Tesi.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-b964094e-4512-7c41-ca17-6a4a18d8b0fa
                host: MSI
                memory:
                    total: "16866521088"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\devam\OneDrive\Tesi\src_python\tune.py
                python: CPython 3.12.3
                root: C:\Users\devam\OneDrive\Tesi
                startedAt: "2026-09-02T14:07:39.295524Z"
                writerId: n6ip4c2o9ll2jnl1k3yecbslm4eq9yge
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 35
                - 41
            "2":
                - 1
                - 35
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.28.1
            "8":
                - 3
            "12": 0.28.1
            "13": windows-amd64
beta:
    value: 0.875
input_size:
    value: 224
learning_rate:
    value: 0.000794202760398061
time_steps:
    value: 5
