_wandb:
    value:
        cli_version: 0.28.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 35
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.28.1
            "8":
                - 3
            "12": 0.28.1
            "13": windows-amd64
beta:
    value: 0.75
input_size:
    value: 112
learning_rate:
    value: 0.00018795081491992938
time_steps:
    value: 6
